config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order('created_at DESC')
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create

    @article = Article.create(article_params)
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container"></div>
<%= form_for @article, html: {class: "form-container"} do |f| %>
<%= f.text_field :title, placeholder: 'What\'s it\'s title?', class: 'form-control input-field' %>
<%= f.text_area :content, placeholder: 'Jot it down! ✍️', class: 'form-control input-field' %>
<%= f.submit "Edit the article", class: 'btn btn-success' %>
<% end %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <article>
    <h2><a href="<%= article.url %>"><%= article.title %></a></h2> - <%= link_to '🗑 Delete this article', article_path(article), method: :delete  %>

    <p><%= article.content %></p>
  </article>
<% end %>

app/views/articles/new.html.erb
<div class="container"></div>
<%= form_for @article, html: {class: "form-container"} do |f| %>
<%= f.text_field :title, placeholder: 'What\'s it\'s title?', class: 'form-control input-field' %>
<%= f.text_area :content, placeholder: 'Jot it down! ✍️', class: 'form-control input-field' %>
<%= f.text_field :url, placeholder: 'https://', class: 'form-control input-field' %>
<%= f.submit "Publish your article", class: 'btn btn-success' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsWikinimous</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="navbar">
    <h1>Wikinimous</h1>
    <p><%= link_to 'New article', new_article_path %></p>
  </div>
  <%= yield %>
</body>
</html>